// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HomepageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void homepage() {
    driver.get("http://127.0.0.1:5500/");
    driver.manage().window().setSize(new Dimension(1430, 805));
    driver.findElement(By.linkText("Home")).click();
    driver.findElement(By.id("home-heading")).click();
    driver.findElement(By.cssSelector(".main-img")).click();
    driver.findElement(By.id("newsletter")).click();
    driver.findElement(By.id("newsletter")).sendKeys("test@example.com");
    driver.findElement(By.id("agree")).click();
    driver.findElement(By.cssSelector("label:nth-child(2) > input")).click();
    driver.findElement(By.cssSelector("label:nth-child(3) > input")).click();
    driver.findElement(By.cssSelector("button")).click();
  }
}
