// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BrowsepageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void browsepage() {
    driver.get("http://127.0.0.1:5500/");
    driver.manage().window().setSize(new Dimension(1430, 805));
    driver.findElement(By.linkText("Browse")).click();
    driver.findElement(By.id("browse-heading")).click();
    driver.findElement(By.cssSelector(".main-img")).click();
    driver.findElement(By.cssSelector("p")).click();
    driver.findElement(By.cssSelector("li:nth-child(1) > button")).click();
    assertThat(driver.switchTo().alert().getText(), is("Charlie 🐶 added to favorites!"));
    driver.findElement(By.cssSelector("li:nth-child(3) > button")).click();
    assertThat(driver.switchTo().alert().getText(), is("Peaches 🦜 added to favorites!"));
    {
      WebElement element = driver.findElement(By.id("friendliness"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("friendliness"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("friendliness"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("friendliness")).click();
    driver.findElement(By.id("reason")).click();
    driver.findElement(By.id("reason")).sendKeys("i love pets");
    driver.findElement(By.cssSelector("button:nth-child(10)")).click();
  }
}
